/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pember

class Aoc {
    val greeting: String
        get() {
            return "Just run the Tests!"
        }
}

fun main(args: Array<String>) {
    println(Aoc().greeting)
}
