/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pember.aoc2020

class App {
    val greeting: String
        get() {
            return "Just rune the Tests!"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
}
